name: network_side
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
   dio: ^5.3.2
   image_picker: ^1.0.1
   shared_preferences: ^2.1.2


dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
